[server]
headless = true
port = 3000
address = "0.0.0.0"
enableCORS = false
maxUploadSize = 5
maxMessageSize = 50

[runner]
magicEnabled = false

[browser]
gatherUsageStats = false

[global]
developmentMode = false