[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
# Light theme colors
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# Dark theme will be handled by streamlit's built-in dark mode